---
- name: Install zsh
  homebrew:
    name: zsh
    state: present

- name: Check if Oh My Zsh is already installed
  stat: path=~/.oh-my-zsh
  register: omzsh_status

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: omzsh_status.stat.isdir is not defined
  ignore_errors: yes
